# Generated by Django 5.0 on 2024-01-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
